config/routes.rb
Rails.application.routes.draw do

  root 'schedules#index'
  get 'schedules/index'

  resources :routes
  resources :vehicles
  resources :drivers

end

app/models/route.rb
class Route < ActiveRecord::Base
  belongs_to :vehicle
  belongs_to :driver
  has_one :schedule
  has_and_belongs_to_many :cities

  scope :without_schedule, ->{joins('LEFT JOIN schedules ON schedules.route_id = routes.id').where('schedules.id IS NULL')}
  has_enumeration_for :load_type, with: ::LoadType, create_scopes: { prefix: true }, create_helpers: true

  accepts_nested_attributes_for :cities
end

app/controllers/routes_controller.rb
class RoutesController < ApplicationController
  before_action :set_route, only: [:show, :edit, :update, :destroy]

  # GET /routes
  # GET /routes.json
  def index
    @routes = Route.all
  end

  # GET /routes/1
  # GET /routes/1.json
  def show
  end

  # GET /routes/new
  def new
    @route = Route.new
  end

  # GET /routes/1/edit
  def edit
  end

  # POST /routes
  # POST /routes.json
  def create
    @route = Route.new(route_params)

    respond_to do |format|
      if @route.save
        format.html { redirect_to @route, notice: 'Route was successfully created.' }
        format.json { render :show, status: :created, location: @route }
      else
        format.html { render :new }
        format.json { render json: @route.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /routes/1
  # PATCH/PUT /routes/1.json
  def update
    respond_to do |format|
      if @route.update(route_params)
        format.html { redirect_to @route, notice: 'Route was successfully updated.' }
        format.json { render :show, status: :ok, location: @route }
      else
        format.html { render :edit }
        format.json { render json: @route.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /routes/1
  # DELETE /routes/1.json
  def destroy
    @route.destroy
    respond_to do |format|
      format.html { redirect_to routes_url, notice: 'Route was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_route
      @route = Route.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def route_params
      params.require(:route).permit(:starts_at, :ends_at, :load_type, :load_sum, :stops_amount, :vehicle_id, :driver_id, city_ids:[])
    end
end

app/helpers/routes_helper.rb
module RoutesHelper
end

app/views/routes/_form.html.erb
<%= form_for(@route) do |f| %>
  <% if @route.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@route.errors.count, "error") %> prohibited this route from being saved:</h2>

      <ul>
      <% @route.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :starts_at %><br>
    <%= f.datetime_select :starts_at %>
  </div>
  <div class="field">
    <%= f.label :ends_at %><br>
    <%= f.datetime_select :ends_at %>
  </div>
  <div class="field">
    <%= f.label :load_type %><br>
    <%= f.select :load_type, LoadType.to_a%>
  </div>
  <div class="field">
    <%= f.label :load_sum %><br>
    <%= f.number_field :load_sum, step: :any  %>
  </div>
  <div class="field">
    <%= f.label :stops_amount %><br>
    <%= f.number_field :stops_amount %>
  </div>

  <div class="field">
    <%= f.label :city_ids %><br>
    <%= f.collection_select :city_ids, City.all, :id, :name, {}, {:multiple => true}%>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/routes/edit.html.erb
<h1>Editing Route</h1>

<%= render 'form' %>

<%= link_to 'Show', @route %> |
<%= link_to 'Back', routes_path %>

app/views/routes/index.html.erb
<p id="notice"><%= notice %></p>
<div class="table-wrapper">
  <div class="table-title">
    <div class="row">
      <div class="col-sm-6">
        <h1>Listing Routes</h1>

  <table class="table table-striped table-hover">
    <thead>
      <tr>
        <th>Starts at</th>
        <th>Ends at</th>
        <th>Load type</th>
        <th>Load sum</th>
        <th>Stops amount</th>
        <th>Vehicle</th>
        <th>Driver</th>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <% @routes.each do |route| %>
        <tr>
          <td><%= route.starts_at %></td>
          <td><%= route.ends_at %></td>
          <td><%= route.load_type %></td>
          <td><%= route.load_sum %></td>
          <td><%= route.stops_amount %></td>
          <td><%= route.vehicle %></td>
          <td><%= route.driver %></td>
          <td><%= link_to 'Show', route %></td>
          <td><%= link_to 'Edit', edit_route_path(route) %></td>
          <td><%= link_to 'Destroy', route, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
      <% end %>
    </tbody>
  </table>

  <br>

  <%= link_to 'New Route', new_route_path %>
</div>

app/views/routes/new.html.erb
<h1>New Route</h1>

<%= render 'form' %>

<%= link_to 'Back', routes_path %>

app/views/routes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Starts at:</strong>
  <%= @route.starts_at %>
</p>

<p>
  <strong>Ends at:</strong>
  <%= @route.ends_at %>
</p>

<p>
  <strong>Load type:</strong>
  <%= @route.load_type %>
</p>

<p>
  <strong>Load sum:</strong>
  <%= @route.load_sum %>
</p>

<p>
  <strong>Stops amount:</strong>
  <%= @route.stops_amount %>
</p>

<p>
  <strong>Vehicle:</strong>
  <%= @route.vehicle %>
</p>

<p>
  <strong>Driver:</strong>
  <%= @route.driver %>
</p>

<%= link_to 'Edit', edit_route_path(@route) %> |
<%= link_to 'Back', routes_path %>