config/routes.rb
Rails.application.routes.draw do

  root 'schedules#index'
  get 'schedules/index'

  resources :routes
  resources :vehicles
  resources :drivers

end

app/models/driver.rb
class Driver < ActiveRecord::Base
  include ScheduleFilters

  has_one :vehicle
  has_many :schedules
  has_and_belongs_to_many :cities

  scope :by_max_stop, ->(max_stops) { where('max_stops >= ?', max_stops) }
  scope :without_vehicle, -> {where("NOT EXISTS #{vehicles_sql}")}
  scope :with_vehicle, -> {where("EXISTS #{vehicles_sql}")}

  accepts_nested_attributes_for :cities

  private

  def self.vehicles_sql
    '(SELECT 1 FROM vehicles WHERE vehicles.driver_id = drivers.id LIMIT 1)'
  end
end

app/models/drivers/zone_filter.rb
module Drivers
  class ZoneFilter
    def initialize(drivers, zones_ids)
      self.drivers = drivers
      self.zones_ids = zones_ids
    end

    def filter_by_preferred_zones
      drivers.includes(:cities).select do |d|
        next if d.city_ids.empty?
        zones_ids.all? { |c_id| d.city_ids.include? (c_id) }
      end
    end

    private

    attr_accessor :drivers, :zones_ids
  end
end

app/controllers/drivers_controller.rb
class DriversController < ApplicationController
  before_action :set_driver, only: [:show, :edit, :update, :destroy]

  # GET /drivers
  # GET /drivers.json
  def index
    @drivers = Driver.all
  end

  # GET /drivers/1
  # GET /drivers/1.json
  def show
  end

  # GET /drivers/new
  def new
    @driver = Driver.new
  end

  # GET /drivers/1/edit
  def edit
  end

  # POST /drivers
  # POST /drivers.json
  def create
    @driver = Driver.new(driver_params)

    respond_to do |format|
      if @driver.save
        format.html { redirect_to @driver, notice: 'Driver was successfully created.' }
        format.json { render :show, status: :created, location: @driver }
      else
        format.html { render :new }
        format.json { render json: @driver.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /drivers/1
  # PATCH/PUT /drivers/1.json
  def update
    respond_to do |format|
      if @driver.update(driver_params)
        format.html { redirect_to @driver, notice: 'Driver was successfully updated.' }
        format.json { render :show, status: :ok, location: @driver }
      else
        format.html { render :edit }
        format.json { render json: @driver.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /drivers/1
  # DELETE /drivers/1.json
  def destroy
    @driver.destroy
    respond_to do |format|
      format.html { redirect_to drivers_url, notice: 'Driver was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_driver
      @driver = Driver.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def driver_params
      params.require(:driver).permit(:name, :phone, :email, :max_stops, city_ids: [])
    end
end

app/helpers/drivers_helper.rb
module DriversHelper
end

app/views/drivers/_form.html.erb
<%= form_for(@driver) do |f| %>
  <% if @driver.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@driver.errors.count, "error") %> prohibited this driver from being saved:</h2>

      <ul>
      <% @driver.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :phone %><br>
    <%= f.text_field :phone %>
  </div>
  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :max_stops %><br>
    <%= f.number_field :max_stops %>
  </div>

  <div class="field">
    <%= f.label :city_ids %><br>
    <%= f.collection_select :city_ids, City.all, :id, :name, {}, {:multiple => true}%>
  </div>


  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/drivers/edit.html.erb
<h1>Editing Driver</h1>

<%= render 'form' %>

<%= link_to 'Show', @driver %> |
<%= link_to 'Back', drivers_path %>

app/views/drivers/index.html.erb
<p id="notice"><%= notice %></p>
<div class="table-wrapper">
  <div class="table-title">
    <div class="row">
      <div class="col-sm-6">
        <h1>Listing Drivers</h1>
      </div>
    </div>
  </div>
  <table class="table table-striped table-hover">
    <thead>
      <tr>
        <th>Name</th>
        <th>Phone</th>
        <th>Email</th>
        <th>Max stops</th>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <% @drivers.each do |driver| %>
        <tr>
          <td><%= driver.name %></td>
          <td><%= driver.phone %></td>
          <td><%= driver.email %></td>
          <td><%= driver.max_stops %></td>
          <td><%= link_to 'Show', driver %></td>
          <td><%= link_to 'Edit', edit_driver_path(driver) %></td>
          <td><%= link_to 'Destroy', driver, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
      <% end %>
    </tbody>
  </table>

<br>

<%= link_to 'New Driver', new_driver_path %>
</div>

app/views/drivers/new.html.erb
<h1>New Driver</h1>

<%= render 'form' %>

<%= link_to 'Back', drivers_path %>

app/views/drivers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @driver.name %>
</p>

<p>
  <strong>Phone:</strong>
  <%= @driver.phone %>
</p>

<p>
  <strong>Email:</strong>
  <%= @driver.email %>
</p>

<p>
  <strong>Max stops:</strong>
  <%= @driver.max_stops %>
</p>

<%= link_to 'Edit', edit_driver_path(@driver) %> |
<%= link_to 'Back', drivers_path %>