config/routes.rb
Rails.application.routes.draw do

  root 'schedules#index'
  get 'schedules/index'

  resources :routes
  resources :vehicles
  resources :drivers

end

app/models/vehicle.rb
class Vehicle < ActiveRecord::Base
  include ScheduleFilters

  belongs_to :driver
  has_many :schedules

  has_enumeration_for :load_type, with: ::LoadType, create_scopes: { prefix: true }, create_helpers: true
  scope :by_capacity, ->(capacity) { where('capacity >= ?', capacity) }
  scope :by_load_type, ->(load_type) { where(load_type: load_type) }
  scope :without_owner, -> { where(driver: nil) }
end

app/controllers/vehicles_controller.rb
class VehiclesController < ApplicationController
  before_action :set_vehicle, only: [:show, :edit, :update, :destroy]

  # GET /vehicles
  # GET /vehicles.json
  def index
    @vehicles = Vehicle.all
  end

  # GET /vehicles/1
  # GET /vehicles/1.json
  def show
  end

  # GET /vehicles/new
  def new
    @vehicle = Vehicle.new
  end

  # GET /vehicles/1/edit
  def edit
  end

  # POST /vehicles
  # POST /vehicles.json
  def create
    @vehicle = Vehicle.new(vehicle_params)

    respond_to do |format|
      if @vehicle.save
        format.html { redirect_to @vehicle, notice: 'Vehicle was successfully created.' }
        format.json { render :show, status: :created, location: @vehicle }
      else
        format.html { render :new }
        format.json { render json: @vehicle.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /vehicles/1
  # PATCH/PUT /vehicles/1.json
  def update
    respond_to do |format|
      if @vehicle.update(vehicle_params)
        format.html { redirect_to @vehicle, notice: 'Vehicle was successfully updated.' }
        format.json { render :show, status: :ok, location: @vehicle }
      else
        format.html { render :edit }
        format.json { render json: @vehicle.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /vehicles/1
  # DELETE /vehicles/1.json
  def destroy
    @vehicle.destroy
    respond_to do |format|
      format.html { redirect_to vehicles_url, notice: 'Vehicle was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_vehicle
      @vehicle = Vehicle.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def vehicle_params
      params.require(:vehicle).permit(:capacity, :load_type, :driver_id)
    end
end

app/helpers/vehicles_helper.rb
module VehiclesHelper
end

app/views/vehicles/_form.html.erb
<%= form_for(@vehicle) do |f| %>
  <% if @vehicle.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@vehicle.errors.count, "error") %> prohibited this vehicle from being saved:</h2>

      <ul>
      <% @vehicle.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :capacity %><br>
    <%= f.number_field :capacity, step: :any  %>
  </div>
  <div class="field">
    <%= f.label :load_type %><br>
    <%= f.select :load_type, LoadType.to_a%>
  </div>
  <div class="field">
    <%= f.label :driver_id %><br>
    <%= f.select :driver_id, Driver.all.collect {|p| [ p.name, p.id ]},{ include_blank: true }%>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/vehicles/edit.html.erb
<h1>Editing Vehicle</h1>

<%= render 'form' %>

<%= link_to 'Show', @vehicle %> |
<%= link_to 'Back', vehicles_path %>

app/views/vehicles/index.html.erb
<p id="notice"><%= notice %></p>
<div class="table-wrapper">
  <div class="table-title">
    <div class="row">
      <div class="col-sm-6">
        <h1>Listing Vehicles</h1>
      </div>
    </div>
  </div>

  <table class="table table-striped table-hover">
    <thead>
      <tr>
        <th>Capacity</th>
        <th>Load type</th>
        <th>Driver</th>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <% @vehicles.each do |vehicle| %>
        <tr>
          <td><%= vehicle.capacity %></td>
          <td><%= vehicle.load_type %></td>
          <td><%= vehicle.driver.try(:name) %></td>
          <td><%= link_to 'Show', vehicle %></td>
          <td><%= link_to 'Edit', edit_vehicle_path(vehicle) %></td>
          <td><%= link_to 'Destroy', vehicle, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
      <% end %>
    </tbody>
  </table>

  <br>

  <%= link_to 'New Vehicle', new_vehicle_path %>
</div>

app/views/vehicles/new.html.erb
<h1>New Vehicle</h1>

<%= render 'form' %>

<%= link_to 'Back', vehicles_path %>

app/views/vehicles/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Capacity:</strong>
  <%= @vehicle.capacity %>
</p>

<p>
  <strong>Load type:</strong>
  <%= @vehicle.load_type %>
</p>

<p>
  <strong>Driver:</strong>
  <%= @vehicle.driver %>
</p>

<%= link_to 'Edit', edit_vehicle_path(@vehicle) %> |
<%= link_to 'Back', vehicles_path %>